### ISSUE TITLE
What camera gear do you use and why?

### ISSUE THREAD

**Issue by iamarya2k24** [dreamingechoes/ama#1]

**Comment by dreamingechoes** [comment]
Hi @Navneet-Suresh!

Nice to meet you! Well, I have a variety of photography gear because I love photography in all its forms, but I personally enjoy analog over digital photography (that's why I have 80% of my gear related with analog photography).

I started like 15 years ago when I fell in love with [Lomography](https://en.wikipedia.org/wiki/Lomography), and I bought a [Holga CFN 120](https://shop.lomography.com/en/holga-cfn-120) and an [ActionSampler](https://shop.lomography.com/en/actionsampler-clear). In the following years, I kept buying Lomo cameras (on eBay you can find second-hand cameras for really cheap), like the [LCA](https://shop.lomography.com/en/lomo-lc-a-rl-old), [Smena 8M](https://shop.lomography.com/en/lomo-smena-8m), [Fisheye](https://shop.lomography.com/en/fisheye-one-red), [Diana F+](https://shop.lomography.com/en/diana-f)... Now I don't use them so much because I'm more into the instant photography, but I still keep them to use them from time to time. I bought an old Polaroid a couple years ago, and some friends gifted me with a [Fuji Instant Mini 90](http://instax.com/mini90/en/), and I love them!

For digital photography, I have an old [Canon 500D](https://en.wikipedia.org/wiki/Canon_EOS_500D) and a [Fujifilm X30](http://www.fujifilmusa.com/products/digital_cameras/x/fujifilm_x30/) (which is which I use the most). The X30 it's quite comfortable and the quality it's amazing, that's why I use it more than the 500D.

But, with a huge difference, the camera I use the most it's the one I have every day in my pocket: my [iPhone SE](https://www.apple.com/iphone-se/). It doesn't have the most impressive mobile phone camera of the market, but I like it, and with a little of post-processing on the photographies with applications like [VSCO](https://vsco.co/), you have an awesome camera.

I hope this answers your question. Oh, btw, thank you for the question!

Greetings! 😄
